### ISSUE TITLE
프레그 먼트에서 onCreateView 에 SuperCall 에러가 있습니다.

### ISSUE THREAD

**Issue by MoonDaeYeong** [skydoves/Bindables#17]
override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View {
    super.onCreateView(inflater, container, savedInstanceState)
    return binding {
      lifecycleOwner = this@SurveyFragment
      vm = viewModel

      setBindItem()
      subscribeUi()

    }.root
  }

에러: Overriding method should call super.onCreateView

implementation 'com.github.skydoves:bindables:1.0.9' 를 사용중입니다.
ext.kotlin_version = "1.5.21" 코틀린 버전

allprojects {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
        maven { url 'https://maven.google.com' }
    }
}

**Comment by skydoves** [comment]
Hi @MoonDaeYeong,
This seems like a [temporary linting issue](https://stackoverflow.com/questions/68465950/overriding-method-should-call-superandroidstudio-kotlin-lint) on your project.

Here are some solutions.

1. invalidating caches & restart, clean project, rebuild project.
2. Add `@SuppressLint("MissingSuperCall")` annotation to your `onCreateView`.

If you still getting the same issue, please report it again on this thread.
Thanks!
