### ISSUE TITLE
BottomSheetDialogFragment - Feature Request

### ISSUE THREAD

**Issue by pauloaapereira** [skydoves/Bindables#2]
First of all thank you so much for this awesome library. Your code is, as usually, really well organized and useful.

*Is your feature request related to a problem?*

I was hoping to implement a BottomSheetDialogFragment, and to use DataBinding on it.
Since I am using Bindables, I was looking for a binding class that would extend already from the BottomSheetDialogFragment class.

*Describe the solution you'd like:*

I know it is not hard to apply some work around from my side to this, but I also think that this would be a good feature to be implemented and made available.

**Comment by skydoves** [comment]
Thanks for your great issue :)
You can use `BindingBottomSheetDialogFragment` in the SNAPSHOT `bindables:1.0.5-SNAPSHOT`.

**Comment by pauloaapereira** [comment]
> Thanks for your great issue :)
> You can use `BindingBottomSheetDialogFragment` in the SNAPSHOT `bindables:1.0.5-SNAPSHOT`.

Thank you, I'll give it a try! :)

**Comment by pauloaapereira** [comment]
Sorry for the late answer! I only managed to test it now.
Working fine, no issues so far.
Thanks! @skydoves
