### ISSUE TITLE
SavedStateHandle default value

### ISSUE THREAD

**Issue by fjr619** [skydoves/Bindables#21]
How to add default value when using savedstatehandle?

```
  @get:Bindable
  var savedPage: Int? by savedStateHandle.asBindingProperty("PAGE")
  ```
  
  So i want this savedPage non nullable, by put default value, thank you

**Comment by skydoves** [comment]
Hi @fjr619, for this case, I recommend just using `getLiveData` as following: 

```kotlin
savedStateHandle.getLiveData("PAGE", 0)
```

Also, `LiveData` can be observed on the DataBinding layer without the Bindable annotation.
